org: ficlel
app: foodappbackend
service: FoodAppBackEnd

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"

plugins:
  - serverless-offline

functions:
  graphql:
    handler: index.graphqlHandler
    events:
      - http:
          path: "{proxy+}"
          method: any
          cors: true
 



